config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'recipes#index'

  # ユーザーのマイページへのルート
  get 'mypage', to: 'users#show'

  resources :recipes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color_group.rb
# app/models/color_group.rb
class ColorGroup < ActiveHash::Base
  self.data = [
    { id: 1, name: '赤' },
    { id: 2, name: '緑' },
    { id: 3, name: '黄' }
  ]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
  validates :quantity, presence: true

  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  serialize :color_group_ids, Array

  # 栄養カテゴリーの全リスト
  COLOR_GROUPS = [1, 2, 3].freeze

  validates :title, presence: true, length: { maximum: 255 }
  validates :instructions, presence: true
  belongs_to :user
  has_many :ingredients, dependent: :destroy

  accepts_nested_attributes_for :ingredients
  has_one_attached :image

  def self.search(keyword, color_group_id)
    recipes = Recipe.all

    if keyword.present?
      recipes = recipes.left_joins(:ingredients).where(
        'recipes.title LIKE ? OR recipes.description LIKE ? OR recipes.instructions LIKE ? OR ingredients.name LIKE ?',
        "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"
      ).distinct
    end

    if color_group_id.present?
      color_group_id = color_group_id.to_s
      recipes = recipes.select { |r| r.color_group_ids.include?(color_group_id) }
    end

    recipes
  end

  def missing_nutrient_categories
    # このレシピに設定されている栄養カテゴリーのIDリストを取得
    current_categories_ids = color_group_ids.map(&:to_i)

    # 全カテゴリーのIDから、現在のレシピのカテゴリーIDを減算して、不足しているカテゴリーIDを特定
    COLOR_GROUPS - current_categories_ids
  end

  # categoryを取得して、不足しているcategoryを充足できるレシピを提案する
  def self.suggest_recipes(missing_nutrients)
    # 文字列として保存されている color_group_ids から、
    # 指定された栄養カテゴリーを含むレシピを検索する
    Recipe.all.select do |recipe|
      (recipe.color_group_ids.map(&:to_i) & missing_nutrients).any?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]+\z/
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数字混合で入力してください。' }, if: lambda {
                                                                                                    new_record? || !password.nil?
                                                                                                  }

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  # GET /recipes
  def index
    @recipes = if params[:keyword].present? || params[:color_group_id].present?
                 Recipe.search(params[:keyword], params[:color_group_id])
               else
                 Recipe.all
               end
  end

  # GET /recipes/1
  def show
    @missing_nutrients = @recipe.missing_nutrient_categories
    @suggested_recipes = Recipe.suggest_recipes(@missing_nutrients)
  end

  # GET /recipes/new
  def new
    if signed_in?
      @recipe = Recipe.new
      @recipe.ingredients.build # 材料の空オブジェクトを生成
    else
      redirect_to root_path, alert: 'ログインが必要です。'
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe.ingredients.build if @recipe.ingredients.empty?
  end

  # POST /recipes
  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'レシピが正常に作成されました。'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'レシピが正常に更新されました。'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    if @recipe.destroy
      flash[:notice] = 'レシピが正常に削除されました。'
    else
      flash[:alert] = 'レシピの削除に失敗しました。'
    end
    redirect_to recipes_url
  end

  private

  # Use callbacks to share common setup or constraints between actions
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def check_owner
    return if @recipe.user == current_user

    redirect_to root_path, alert: 'この操作を実行する権限がありません。'
  end

  def suggest_recipes(missing_nutrients)
    # 不足している栄養カテゴリーに対応するレシピを検索
    Recipe.where('color_group_ids @> ARRAY[?]::integer[]', missing_nutrients).limit(5)
  end

  # Only allow a list of trusted parameters through
  def recipe_params
    params.require(:recipe).permit(
      :title,
      :description,
      :instructions,
      :image,
      { color_group_ids: [] },
      ingredients_attributes: [:id, :name, :quantity, :_destroy]
    ).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

    # ログインユーザーのレシピを取得する
    if signed_in?
      @recipes = current_user.recipes
    else
      redirect_to root_path, alert: 'ログインが必要です。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マイレシピアプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>">
        <%= message %>
      </div>
    <% end %>

    <header class="header main-header">
      <div class="container">
        <div class="title-and-icon">
          <%= link_to "マイレシピアプリ", root_path, class: "logo" %>
          <%= link_to root_path, class: "header-icon" do %>
            <%= image_tag 'myrecipeicon.png', alt: 'アイコン' %>
          <% end %>
        </div>
      </div>
    </header>

  <%= yield %>

    <footer class="footer">
      <div class="container">
        <p class="footer-text">&copy; <%= Time.now.year %> MyRecipeApp. All rights reserved.</p>
      </div>
    </footer>

  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true, html: { class: 'container' }) do |form| %>
  <% if recipe.errors.any? %>
  <div>
    <h2><%= pluralize(recipe.errors.count, "error") %> が検出されました：</h2>
    <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="recipe-form">
    <div>
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :description, "説明" %>
      <%= form.text_area :description %>
    </div>

    <div>
      <%= form.label :image, "画像", for: 'image-preview'  %>
      <%= form.file_field :image, id: 'image-preview', direct_upload: true %>
      <div id="preview-container" style="margin-top: 20px;">
        <% if recipe.image.attached? %>
          <h3>画像プレビュー</h3> <!-- 見出し -->
          <%= image_tag recipe.image, id: 'image-preview-tag', style: 'max-width: 200px;' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="recipe-form">
    <h2>材料と分量</h2>
    <table id="ingredients_table">
      <thead>
        <tr>
          <th>材料</th>
          <th>分量</th>
          <th>削除</th>
        </tr>
      </thead>
      <tbody>
        <%= form.fields_for :ingredients do |ingredient_form| %>
          <tr>
            <td><%= ingredient_form.text_field :name, placeholder: "材料名" %></td>
            <td><%= ingredient_form.text_field :quantity, placeholder: "分量" %></td>
            <td><%= link_to '削除', '#', class: "remove_fields" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to '材料を追加', '#', id: "add_ingredient", class: "button" %>
  </div>

  <div>
    <%= form.label :instructions, "作り方" %>
    <%= form.text_area :instructions %>
  </div>


<div class="food-group-container">
  <div class="food-group-checkboxes">
    <div class="field">
      <h3>食品群</h3>
      <% ColorGroup.all.each do |color_group| %>
        <%= form.check_box :color_group_ids, {
          multiple: true,
          id: "color_group_ids_#{color_group.id}",
          checked: recipe.color_group_ids.include?(color_group.id.to_s)
        }, color_group.id, nil %>
        <%= label_tag "color_group_ids_#{color_group.id}", color_group.name %><br>
      <% end %>
    </div>
  </div>
  <div class="food-group-image">
    <%= image_tag '3-color-food-groups.png', alt: '3色の食品群' %>
    <%# <h5>※出展：佐世保市役所</h5> %>
  </div>
</div>


  <div class="return-button">
    <%= form.submit recipe.new_record? ? "レシピを登録" : "レシピを更新" %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<tr>
  <td><input type="text" name="recipe[ingredients_attributes][][name]" placeholder="材料名"></td>
  <td><input type="text" name="recipe[ingredients_attributes][][quantity]" placeholder="分量"></td>
  <td><a href="#" class="remove_fields">削除</a></td>
</tr>

app/views/recipes/edit.html.erb
<div class="page-container">
  <h1>レシピの編集</h1>
</div>

<%= render 'form', recipe: @recipe %>

<div class="page-container">
  <%= link_to '一覧に戻る', recipes_path %>
</div>

app/views/recipes/find.html.erb
<!-- search_results.html -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>検索結果</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<h2>検索結果</h2>
<ul>
    <!-- 各レシピのリストアイテム -->
    <li><a href="recipe_detail.html">レシピ1</a></li>
    <li><a href="recipe_detail.html">レシピ2</a></li>
    <!-- その他のレシピ -->
</ul>
</body>
</html>

app/views/recipes/index.html.erb
<header class="header recipes-header">
    <div class="user-menu">
        <% if user_signed_in? %>
            <%= link_to 'プロフィール', edit_user_registration_path, class: "menu-link" %>
            <%= link_to 'レシピ投稿', new_recipe_path, class: "menu-link"  %>
            <%= link_to 'マイページ', mypage_path, class: "menu-link"  %>
            <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "menu-link"  %>
        <% else %>
            <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
    </div>
    <%= form_with url: recipes_path, method: :get do |form| %>
        <div class="container">
            <%= form.label :keyword, 'キーワード' %>
            <%= form.text_field :keyword %>
        </div>
        <div class="container">
            <%= form.label :color_group_id, 'カテゴリー' %>
            <%= form.select :color_group_id, ColorGroup.all.map { |c| [c.name, c.id] }, include_blank: true %>
        </div>
        <div class="return-button">
            <%= form.submit '検索', class: 'button' %>
        </div>
    <% end %>
</header>

<div class="page-container">
    <h1>レシピ一覧</h1>
    <div class="container">
        <ul class="recipe-list">
            <% @recipes.each do |recipe| %>
                <li>
                    <div class="recipe-item">
                        <% if recipe.image.attached? %>
                            <%= link_to image_tag(recipe.image), recipe_path(recipe) %>
                        <% else %>
                            <%= link_to image_tag('default-salad.png', alt: 'サンプルサラダ画像'), recipe_path(recipe) %>
                        <% end %>
                        <h3><%= link_to recipe.title, recipe %></h3>
                        <% if current_user == recipe.user %>
                            <%= link_to '編集', edit_recipe_path(recipe) %>
                            <%= link_to '削除', recipe_path(recipe), method: :delete, data: { turbo_confirm: '本当に削除しますか？', turbo_method: :delete } %>
                        <% end %>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1>新しいレシピ</h1>
</div>

<%= render 'form', recipe: @recipe %>

<div class="container">
  <%= link_to '一覧に戻る', recipes_path %>
</div>

app/views/recipes/show.html.erb
<div class="page-container">
  <div class="container">

    <!-- レシピタイトルと画像 -->
    <div class="recipe-form">
      <h1 class="title"><%= @recipe.title %></h1>
      <% if @recipe.image.attached? %>
          <%= image_tag @recipe.image, class: "recipe-image" %>
      <% else %>
          <%= image_tag 'default-salad.png', alt: 'サンプルサラダ画像', class: "recipe-image"  %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <!-- レシピ説明 -->
    <div class="recipe-form">
      <h2>説明</h2>
      <p><%= @recipe.description %></p>
    </div>
  </div>

  <div class="container">
    <!-- 食品群セクション -->
    <div class="recipe-form">
      <h3>食品群</h3>
      <% ColorGroup.all.each do |color_group| %>
        <%= check_box_tag "color_group_ids_#{color_group.id}",
          color_group.id, @recipe.color_group_ids.include?(color_group.id.to_s), disabled: true %>
        <%= label_tag "color_group_ids_#{color_group.id}", color_group.name %><br>
      <% end %>
    </div>
  </div>

  <div class="container">
    <!-- 材料リスト -->
    <div class="recipe-form">
      <h2>材料と分量</h2>
      <ul class="no-list-style">
        <% @recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient.name %> - <%= ingredient.quantity %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container">
    <div class="recipe-form">
      <h2>調理手順</h2>
      <p><%= @recipe.instructions %></p>
    </div>
  </div>

  <div class="container">
    <!-- 不足している栄養を補うおすすめレシピ -->
    <div class="recipes-form">
      <h3>不足している栄養を補うおすすめレシピ</h3>
      <div class="recipes-container">
        <% if @suggested_recipes.empty? %>
          <p>このレシピは栄養バランスが取れています。</p>
        <% else %>
          <% @suggested_recipes.each do |recipe| %>
            <div class="recipe-item">
              <%# 提案レシピタイトルと画像 %>
              <%= link_to recipe.title, recipe_path(recipe) %></br>
              <% if recipe.image.attached? %>
                <%= link_to image_tag(recipe.image), recipe_path(recipe) %>
              <% else %>
                <%= link_to image_tag('default-salad.png', alt: 'サンプルサラダ画像'), recipe_path(recipe) %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <!-- 編集ボタンと一覧に戻るボタン -->
    <div class="recipe-form">
      <% if current_user == @recipe.user %>
        <%= link_to '編集', edit_recipe_path(@recipe) %></br>
      <% end %>
      <%= link_to '一覧に戻る', recipes_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<header class="header recipes-header">
    <div class="user-menu">
        <%= link_to 'プロフィール', edit_user_registration_path, class: "menu-link" %>
        <%= link_to 'レシピ投稿', new_recipe_path, class: "menu-link" %>
        <%= link_to 'トップページ', root_path, class: "menu-link" %>
        <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "menu-link" %>
    </div>
</header>

<div class="page-container">
    <h1>マイレシピ</h1> <!-- マイページのタイトル -->
    <div class="container">
        <ul class="recipe-list">
            <% @recipes.each do |recipe| %>
                <li>
                    <div class="recipe-item">
                        <% if recipe.image.attached? %>
                            <%= link_to image_tag(recipe.image), recipe_path(recipe) %>
                        <% else %>
                            <%= link_to image_tag('default-salad.png', alt: 'サンプルサラダ画像'), recipe_path(recipe) %>
                        <% end %>
                        <h3><%= link_to recipe.title, recipe %></h3>
                        <!-- 自分のレシピに対して編集・削除リンクを表示 -->
                        <%= link_to '編集', edit_recipe_path(recipe) %>
                        <%= link_to '削除', recipe_path(recipe), method: :delete, data: { turbo_confirm: '本当に削除しますか？', turbo_method: :delete } %>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>